modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT Lisense"
issueTrackerURL="https://github.com/Bowa1000/dynamic-clothes-mod/issues" #optional
[[mods]] #mandatory
modId="dynamicclothes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dynamic Clothes" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="clothes.png" #optional
credits="My friend LycanDID wanted this as its own mod, so here it is. ^w^" #optional
authors="Bowa1000" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description='''
A mod to give players a swapable texture layer on top of their skins.
'''
[[dependencies.dynamicclothes]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dynamicclothes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dynamicclothes]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.2.2,)"
    ordering="NONE"
    side="BOTH"
